name: Send release notifications
# Send notification on build complete, either success or failure
on:
  push:
    branches:
      - main
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on completion
        if: always()
        uses: rtCamp/action-slack-notify@v2.1.0
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Discord Notification
        id: discord-notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ steps.notification.outputs.message }}
